
test: ChooseMission.o
	g++ -g -o test ChooseMission.cpp -L/usr/local/boost_1_55_0/stage/lib/ -lboost_system -lboost_filesystem 


ChooseMission.o: ChooseMission.cpp ChooseMission.h
	g++ -g -c ChooseMission.cpp